In [2]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [4]:
df = sns.load_dataset('iris')
df

,sepal_length,sepal_width,petal_length,petal_width,species
0,5.1,3.5,1.4,0.2,setosa
1,4.9,3.0,1.4,0.2,setosa
2,4.7,3.2,1.3,0.2,setosa
3,4.6,3.1,1.5,0.2,setosa
4,5.0,3.6,1.4,0.2,setosa
...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,virginica
146,6.3,2.5,5.0,1.9,virginica
147,6.5,3.0,5.2,2.0,virginica
148,6.2,3.4,5.4,2.3,virginica


In [6]:
df.head()

,sepal_length,sepal_width,petal_length,petal_width,species
0,5.1,3.5,1.4,0.2,setosa
1,4.9,3.0,1.4,0.2,setosa
2,4.7,3.2,1.3,0.2,setosa
3,4.6,3.1,1.5,0.2,setosa
4,5.0,3.6,1.4,0.2,setosa


In [8]:
df.tail()

,sepal_length,sepal_width,petal_length,petal_width,species
145,6.7,3.0,5.2,2.3,virginica
146,6.3,2.5,5.0,1.9,virginica
147,6.5,3.0,5.2,2.0,virginica
148,6.2,3.4,5.4,2.3,virginica
149,5.9,3.0,5.1,1.8,virginica


In [10]:
df.describe()

,sepal_length,sepal_width,petal_length,petal_width
count,150.000000,150.000000,150.000000,150.000000
mean,5.843333,3.057333,3.758000,1.199333
std,0.828066,0.435866,1.765298,0.762238
min,4.300000,2.000000,1.000000,0.100000
25%,5.100000,2.800000,1.600000,0.300000
50%,5.800000,3.000000,4.350000,1.300000
75%,6.400000,3.300000,5.100000,1.800000
max,7.900000,4.400000,6.900000,2.500000


In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [14]:
x = df.drop('species',axis=1)
y = df['species']

In [16]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=40)
print(x_train.shape)

(120, 4)


In [19]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()
model.fit(x_train,y_train)

GaussianNB()

In [20]:
y_pred = model.predict(x_test)
print(y_pred)

['setosa' 'versicolor' 'virginica' 'virginica' 'versicolor' 'virginica'
 'versicolor' 'versicolor' 'versicolor' 'setosa' 'versicolor' 'setosa'
 'setosa' 'virginica' 'versicolor' 'virginica' 'virginica' 'virginica'
 'versicolor' 'versicolor' 'virginica' 'virginica' 'versicolor' 'setosa'
 'versicolor' 'setosa' 'setosa' 'virginica' 'setosa' 'versicolor']


In [24]:
from sklearn.metrics import confusion_matrix,recall_score,precision_score,accuracy_score
cm = confusion_matrix(y_test,y_pred)
print(cm)

[[ 8  0  0]
 [ 0 12  0]
 [ 0  0 10]]


In [27]:
accu = accuracy_score(y_test,y_pred)
print(accu)

1.0


In [28]:
error = 1-accu
print(error)

0.0


In [30]:
rec = recall_score(y_test,y_pred,average="macro")
print(rec)

1.0


In [31]:
pre = precision_score(y_test,y_pred,average="macro")
print(pre)

1.0


In [34]:
n = cm.shape[0]
print(n)

3


In [35]:
for i in range (n):
    tp = cm[i,i]
    fp = cm[:,i].sum()-tp
    fn = cm[i,:].sum()-tp
    tn = cm.sum()-(tp+fp+fn)
    print(f"tp={tp},fp={fp},fn={fn},tn={tn}")
    

tp=8,fp=0,fn=0,tn=22
tp=12,fp=0,fn=0,tn=18
tp=10,fp=0,fn=0,tn=20
